pub const VMCLEAR_INVALID_PHYSICAL_ADDRESS_ERROR: u32 = 2;
pub const VMCLEAR_VMXON_POINTER_ERROR: u32 = 3;
pub const VMPTRLD_INVALID_PHYSICAL_ADDRESS_ERROR: u32 = 9;
pub const VMPTRLD_VMXON_POINTER_ERROR: u32 = 10;
pub const VMPTRLD_INCORRECT_REVISION_ERROR: u32 = 11;
pub const VMCS_UNSUPPORTED_COMPONENT_ERROR: u32 = 12;
pub const VMWRITE_READ_ONLY_COMPONENT_ERROR: u32 = 13;

pub const VMX_STATUS_FLAGS: u32 = (1 << 0) | (1 << 2) | (1 << 4) | (1 << 6) | (1 << 7) | (1 << 11);
pub const VMX_STATUS_FLAGS_CLEAR_MASK: i32 = !(VMX_STATUS_FLAGS as i32);
pub const VMFAIL_INVALID_STATUS: u32 = 1 << 0;
pub const VMFAIL_VALID_STATUS: u32 = 1 << 6;
