[package]
name = "neo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pdb = "0.8.0"
colored = "2.1"
ed25519-dalek = { version = "2.2.0", default-features = false }
sha2 = { version = "0.10.9", default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
ureq = "2.12.1"

[target.'cfg(not(target_os = "windows"))'.dependencies]
shlex = "1.3"
