use core::arch::global_asm;
use core::ffi::c_void;

use uefi::boot;
use uefi::proto::pi::mp::MpServices;

use crate::hv_core::vt_resident::{ResidentApLaunch, ResidentProbeError};

pub(crate) fn launch(
    processor_number: usize,
    launch: &mut ResidentApLaunch<'_>,
) -> Result<(), ResidentProbeError> {
    let handle = boot::get_handle_for_protocol::<MpServices>()
        .map_err(|error| ResidentProbeError::Allocation(error.status()))?;
    let mp = boot::open_protocol_exclusive::<MpServices>(handle)
        .map_err(|error| ResidentProbeError::Allocation(error.status()))?;
    mp.startup_this_ap(
        processor_number,
        callback,
        (launch as *mut ResidentApLaunch<'_>).cast(),
        None,
        None,
    )
    .map_err(|error| ResidentProbeError::Allocation(error.status()))
}

extern "efiapi" fn callback(argument: *mut c_void) {
    unsafe {
        matrixhv_ap_launch_asm(argument);
    }
}

#[unsafe(no_mangle)]
unsafe extern "efiapi" fn matrixhv_ap_prepare(
    argument: *mut ResidentApLaunch<'_>,
    guest_rsp: u64,
    guest_rip: u64,
) -> u64 {
    let launch = unsafe { &mut *argument };
    match launch.prepare(guest_rsp, guest_rip) {
        Ok(nested_vmxon_operand) => nested_vmxon_operand,
        Err(error) => {
            crate::runtime::logger::error(format_args!("smp resident AP prepare error={error:?}"));
            0
        }
    }
}

unsafe extern "efiapi" {
    fn matrixhv_ap_launch_asm(argument: *mut c_void);
}

#[unsafe(no_mangle)]
extern "efiapi" fn matrixhv_ap_launch_failed(flags: u64) -> ! {
    let error =
        crate::hv_core::vt_vmcs::vmread(crate::hv_core::vt_vmcs_fields::VM_INSTRUCTION_ERROR);
    crate::runtime::logger::error(format_args!(
        "smp resident AP VMLAUNCH failed flags={flags:#x} instruction_error={error:?}"
    ));
    loop {
        unsafe {
            core::arch::asm!("cli", "hlt", options(nomem, nostack));
        }
    }
}

// The guest resumes on the firmware stack and returns through the original MP callback.
// Only the persistent exit stack and VMCS remain owned by root after this point.
global_asm!(
    ".text",
    ".globl matrixhv_ap_launch_asm",
    "matrixhv_ap_launch_asm:",
    "pushfq",
    "cli",
    "push rbx",
    "push rbp",
    "push rsi",
    "push rdi",
    "push r12",
    "push r13",
    "push r14",
    "push r15",
    "sub rsp, 544",
    "fxsave64 [rsp + 32]",
    "mov rdx, rsp",
    "lea r8, [rip + .Lap_guest_return]",
    "call matrixhv_ap_prepare",
    "test rax, rax",
    "jz .Lap_restore",
    "vmlaunch",
    // A failed launch cannot release resources while another CPU may be resident.
    "pushfq",
    "pop rcx",
    "call matrixhv_ap_launch_failed",
    ".Lap_guest_return:",
    "mov r8, qword ptr [rax + 8]",
    "mov r9, qword ptr [rax + 16]",
    "vmxon [rax]",
    "jna .Lap_nested_probe_failed",
    "vmclear [r8]",
    "jna .Lap_nested_probe_failed",
    "vmptrld [r8]",
    "jna .Lap_nested_probe_failed",
    "vmxon [rax]",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 0x40",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {instruction_error_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {vmxon_active_error}",
    "jne .Lap_nested_probe_failed",
    "vmptrst [r9]",
    "jna .Lap_nested_probe_failed",
    "mov r10, qword ptr [r8]",
    "cmp qword ptr [r9], r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "mov rdx, {vmcs12_test_value}",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "mov r10, {vmcs12_test_value}",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "vmlaunch",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 64",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {instruction_error_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {invalid_control_error}",
    "jne .Lap_nested_probe_failed",
    "vmresume",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 64",
    "jne .Lap_nested_probe_failed",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {non_launched_error}",
    "jne .Lap_nested_probe_failed",
    "vmclear [r8]",
    "jna .Lap_nested_probe_failed",
    "vmlaunch",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 1",
    "jne .Lap_nested_probe_failed",
    "vmresume",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 1",
    "jne .Lap_nested_probe_failed",
    "vmptrld [r8]",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "lea rdx, [rip + .Lap_nested_l2_entry]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {guest_rsp_field}",
    "mov rdx, rsp",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {guest_rflags_field}",
    "mov rdx, 2",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {host_rip_field}",
    "lea rdx, [rip + .Lap_nested_l1_exit]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {host_rsp_field}",
    "mov rdx, rsp",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "vmlaunch",
    "jmp .Lap_nested_probe_failed",
    ".Lap_nested_l2_entry:",
    "mov rax, {l2_vmcall_magic}",
    ".Lap_nested_l2_vmcall:",
    "vmcall",
    ".Lap_nested_l2_after_first:",
    "mov r10, {l2_vmresume_magic}",
    "cmp rax, r10",
    "jne .Lap_nested_l2_bad_resume",
    ".Lap_nested_l2_resume_vmcall:",
    "vmcall",
    ".Lap_nested_l2_bad_resume:",
    "ud2",
    ".Lap_nested_l1_exit:",
    "mov r10, {l2_vmcall_magic}",
    "cmp rax, r10",
    "je .Lap_nested_l1_first_exit",
    "mov r10, {l2_vmresume_magic}",
    "cmp rax, r10",
    "je .Lap_nested_l1_resume_exit",
    "jmp .Lap_nested_probe_failed",
    ".Lap_nested_l1_first_exit:",
    "mov rcx, {exit_reason_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "and edx, 0xffff",
    "cmp edx, 18",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "lea r10, [rip + .Lap_nested_l2_vmcall]",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {exit_instruction_len_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, 3",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "lea rdx, [rip + .Lap_nested_l2_after_first]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rax, {l2_vmresume_magic}",
    "vmresume",
    "jmp .Lap_nested_probe_failed",
    ".Lap_nested_l1_resume_exit:",
    "mov rcx, {exit_reason_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "and edx, 0xffff",
    "cmp edx, 18",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "lea r10, [rip + .Lap_nested_l2_resume_vmcall]",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {exit_instruction_len_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, 3",
    "jne .Lap_nested_probe_failed",
    "vmxoff",
    "jna .Lap_nested_probe_failed",
    "mov eax, 1",
    "xor ecx, ecx",
    "cpuid",
    "test ecx, 0x20",
    "jnz .Lap_nested_probe_failed",
    "test ecx, 0x80000000",
    "jnz .Lap_cpuid_done",
    "mov eax, 0x40000000",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    "mov eax, 0x40000003",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    "mov eax, 0x40000010",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    "mov eax, 0x40000100",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    ".Lap_cpuid_done:",
    "mov rax, 0x4856415052454144",
    "vmcall",
    "jmp .Lap_restore",
    ".Lap_nested_probe_failed:",
    "mov rax, {nested_probe_failed}",
    "vmcall",
    ".Lap_restore:",
    "fxrstor64 [rsp + 32]",
    "add rsp, 544",
    "pop r15",
    "pop r14",
    "pop r13",
    "pop r12",
    "pop rdi",
    "pop rsi",
    "pop rbp",
    "pop rbx",
    "popfq",
    "ret",
    nested_probe_failed = const crate::hv_core::vt_resident::RESIDENT_VMCALL_NESTED_PROBE_FAILED,
    guest_rip_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_RIP,
    guest_rsp_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_RSP,
    guest_rflags_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_RFLAGS,
    host_rip_field = const crate::nested::vmcs::VMCS_FIELD_HOST_RIP,
    host_rsp_field = const crate::nested::vmcs::VMCS_FIELD_HOST_RSP,
    exit_reason_field = const crate::nested::vmcs::VMCS_FIELD_VM_EXIT_REASON,
    exit_instruction_len_field = const crate::nested::vmcs::VMCS_FIELD_VM_EXIT_INSTRUCTION_LEN,
    instruction_error_field = const crate::nested::vmcs::VMCS_FIELD_VM_INSTRUCTION_ERROR,
    vmxon_active_error = const crate::nested::instructions::VMXON_IN_VMX_ROOT_ERROR,
    invalid_control_error = const crate::nested::instructions::VM_ENTRY_INVALID_CONTROL_FIELDS_ERROR,
    non_launched_error = const crate::nested::instructions::VMRESUME_NON_LAUNCHED_VMCS_ERROR,
    vmcs12_test_value = const crate::hv_core::vt_resident::NESTED_VMCS12_TEST_VALUE,
    l2_vmcall_magic = const crate::hv_core::vt_resident::NESTED_L2_VMCALL_MAGIC,
    l2_vmresume_magic = const crate::hv_core::vt_resident::NESTED_L2_VMRESUME_MAGIC,
);
