use core::arch::global_asm;
use core::ffi::c_void;

use uefi::boot;
use uefi::proto::pi::mp::MpServices;

use crate::hv_core::vt_resident::{ResidentApLaunch, ResidentProbeError};

pub(crate) fn launch(
    processor_number: usize,
    launch: &mut ResidentApLaunch<'_>,
) -> Result<(), ResidentProbeError> {
    let handle = boot::get_handle_for_protocol::<MpServices>()
        .map_err(|error| ResidentProbeError::Allocation(error.status()))?;
    let mp = boot::open_protocol_exclusive::<MpServices>(handle)
        .map_err(|error| ResidentProbeError::Allocation(error.status()))?;
    mp.startup_this_ap(
        processor_number,
        callback,
        (launch as *mut ResidentApLaunch<'_>).cast(),
        None,
        None,
    )
    .map_err(|error| ResidentProbeError::Allocation(error.status()))
}

extern "efiapi" fn callback(argument: *mut c_void) {
    unsafe {
        matrixhv_ap_launch_asm(argument);
    }
}

#[unsafe(no_mangle)]
unsafe extern "efiapi" fn matrixhv_ap_prepare(
    argument: *mut ResidentApLaunch<'_>,
    guest_rsp: u64,
    guest_rip: u64,
) -> u64 {
    let launch = unsafe { &mut *argument };
    match launch.prepare(guest_rsp, guest_rip) {
        Ok(nested_vmxon_operand) => nested_vmxon_operand,
        Err(error) => {
            crate::runtime::logger::error(format_args!("smp resident AP prepare error={error:?}"));
            0
        }
    }
}

unsafe extern "efiapi" {
    fn matrixhv_ap_launch_asm(argument: *mut c_void);
}

#[unsafe(no_mangle)]
extern "efiapi" fn matrixhv_ap_launch_failed(flags: u64) -> ! {
    let error =
        crate::hv_core::vt_vmcs::vmread(crate::hv_core::vt_vmcs_fields::VM_INSTRUCTION_ERROR);
    crate::runtime::logger::error(format_args!(
        "smp resident AP VMLAUNCH failed flags={flags:#x} instruction_error={error:?}"
    ));
    loop {
        unsafe {
            core::arch::asm!("cli", "hlt", options(nomem, nostack));
        }
    }
}

// The guest resumes on the firmware stack and returns through the original MP callback.
// Only the persistent exit stack and VMCS remain owned by root after this point.
global_asm!(
    ".text",
    ".globl matrixhv_ap_launch_asm",
    "matrixhv_ap_launch_asm:",
    "pushfq",
    "cli",
    "push rbx",
    "push rbp",
    "push rsi",
    "push rdi",
    "push r12",
    "push r13",
    "push r14",
    "push r15",
    "sub rsp, 544",
    "fxsave64 [rsp + 32]",
    "mov rdx, rsp",
    "lea r8, [rip + .Lap_guest_return]",
    "call matrixhv_ap_prepare",
    "test rax, rax",
    "jz .Lap_restore",
    "vmlaunch",
    // A failed launch cannot release resources while another CPU may be resident.
    "pushfq",
    "pop rcx",
    "call matrixhv_ap_launch_failed",
    ".Lap_guest_return:",
    "mov r8, qword ptr [rax + 8]",
    "mov r9, qword ptr [rax + 16]",
    "mov rbx, rax",
    "vmxon [rax]",
    "jna .Lap_nested_probe_failed",
    "vmclear [r8]",
    "jna .Lap_nested_probe_failed",
    "vmptrld [r8]",
    "jna .Lap_nested_probe_failed",
    "vmxon [rax]",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 0x40",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {instruction_error_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {vmxon_active_error}",
    "jne .Lap_nested_probe_failed",
    "vmptrst [r9]",
    "jna .Lap_nested_probe_failed",
    "mov r10, qword ptr [r8]",
    "cmp qword ptr [r9], r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "mov rdx, {vmcs12_test_value}",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "mov r10, {vmcs12_test_value}",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {exception_bitmap_field}",
    "mov edx, 0x40",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, 0x40",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_cr3_field}",
    "mov rdx, cr3",
    "mov r10, rdx",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {host_cr3_field}",
    "mov rdx, cr3",
    "mov r10, rdx",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_cr0_field}",
    "mov rdx, cr0",
    "mov r10, rdx",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {host_cr0_field}",
    "mov rdx, r10",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_cr4_field}",
    "mov rdx, cr4",
    "mov r10, rdx",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {host_cr4_field}",
    "mov rdx, r10",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov ecx, {sysenter_cs_msr}",
    "rdmsr",
    "shl rdx, 32",
    "or rdx, rax",
    "mov r10, rdx",
    "mov rcx, {guest_sysenter_cs_field}",
    "vmwrite rcx, r10",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {host_sysenter_cs_field}",
    "vmwrite rcx, r10",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov ecx, {sysenter_esp_msr}",
    "rdmsr",
    "shl rdx, 32",
    "or rdx, rax",
    "mov r10, rdx",
    "mov rcx, {guest_sysenter_esp_field}",
    "vmwrite rcx, r10",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {host_sysenter_esp_field}",
    "vmwrite rcx, r10",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov ecx, {sysenter_eip_msr}",
    "rdmsr",
    "shl rdx, 32",
    "or rdx, rax",
    "mov r10, rdx",
    "mov rcx, {guest_sysenter_eip_field}",
    "vmwrite rcx, r10",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {host_sysenter_eip_field}",
    "vmwrite rcx, r10",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "vmlaunch",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 64",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {instruction_error_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {invalid_control_error}",
    "jne .Lap_nested_probe_failed",
    "vmresume",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 64",
    "jne .Lap_nested_probe_failed",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {non_launched_error}",
    "jne .Lap_nested_probe_failed",
    "vmclear [r8]",
    "jna .Lap_nested_probe_failed",
    "vmlaunch",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 1",
    "jne .Lap_nested_probe_failed",
    "vmresume",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 1",
    "jne .Lap_nested_probe_failed",
    "vmptrld [r8]",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {exception_bitmap_field}",
    "xor edx, edx",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {pin_based_control_field}",
    "xor edx, edx",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "test edx, edx",
    "jnz .Lap_nested_probe_failed",
    "mov rcx, {primary_control_field}",
    "mov edx, {primary_activate_secondary_controls}",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {primary_activate_secondary_controls}",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {secondary_control_field}",
    "mov edx, {secondary_enable_ept}",
    "or edx, {secondary_enable_vpid}",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "mov r10d, {secondary_enable_ept}",
    "or r10d, {secondary_enable_vpid}",
    "cmp edx, r10d",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {vpid_field}",
    "mov edx, 1",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, 1",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {ept_pointer_field}",
    "mov rdx, qword ptr [rbx + 24]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp rdx, qword ptr [rbx + 24]",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {vm_exit_controls_field}",
    "mov edx, {vm_exit_host_address_space_size}",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {vm_exit_host_address_space_size}",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {vm_entry_controls_field}",
    "mov edx, {vm_entry_ia32e_mode_guest}",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "xor edx, edx",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {vm_entry_ia32e_mode_guest}",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "lea rdx, [rip + .Lap_nested_l2_entry]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {guest_rsp_field}",
    "mov rdx, rsp",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {guest_rflags_field}",
    "mov rdx, 2",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {host_rip_field}",
    "lea rdx, [rip + .Lap_nested_l1_exit]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rcx, {host_rsp_field}",
    "mov rdx, rsp",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov r14, qword ptr [rbx + 32]",
    "mov r15, qword ptr [rbx + 40]",
    "mov r10, qword ptr [r14]",
    "mov r11, {ept_source_marker}",
    "cmp r10, r11",
    "jne .Lap_nested_probe_failed",
    "mov r10, qword ptr [r15]",
    "mov r11, {ept_target_marker}",
    "cmp r10, r11",
    "jne .Lap_nested_probe_failed",
    "vmlaunch",
    "jmp .Lap_nested_probe_failed",
    ".Lap_nested_l2_entry:",
    "mov r13, qword ptr [r14]",
    "mov r11, {ept_target_marker}",
    "cmp r13, r11",
    "jne .Lap_nested_l2_bad_resume",
    "mov rax, {l2_vmcall_magic}",
    ".Lap_nested_l2_vmcall:",
    "vmcall",
    ".Lap_nested_l2_after_first:",
    "mov r13, qword ptr [r14]",
    "mov r11, {ept_target_marker}",
    "cmp r13, r11",
    "jne .Lap_nested_l2_bad_resume",
    "mov r10, {l2_vmresume_magic}",
    "cmp rax, r10",
    "jne .Lap_nested_l2_bad_resume",
    ".Lap_nested_l2_before_invept_vmcall:",
    "vmcall",
    ".Lap_nested_l2_after_invept:",
    "mov r13, qword ptr [r14]",
    "mov r11, {ept_second_target_marker}",
    "cmp r13, r11",
    "jne .Lap_nested_l2_bad_resume",
    "mov r10, {l2_post_invept_magic}",
    "cmp rax, r10",
    "jne .Lap_nested_l2_bad_resume",
    ".Lap_nested_l2_after_invept_vmcall:",
    "vmcall",
    ".Lap_nested_l2_bad_resume:",
    "ud2",
    ".Lap_nested_l1_exit:",
    "mov r10, {l2_vmcall_magic}",
    "cmp rax, r10",
    "je .Lap_nested_l1_first_exit",
    "mov r10, {l2_vmresume_magic}",
    "cmp rax, r10",
    "je .Lap_nested_l1_resume_exit",
    "mov r10, {l2_post_invept_magic}",
    "cmp rax, r10",
    "je .Lap_nested_l1_after_invept_exit",
    "jmp .Lap_nested_probe_failed",
    ".Lap_nested_l1_first_exit:",
    "mov rcx, {exit_reason_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "and edx, 0xffff",
    "cmp edx, 18",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "lea r10, [rip + .Lap_nested_l2_vmcall]",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {exit_instruction_len_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, 3",
    "jne .Lap_nested_probe_failed",
    "mov r11, {ept_target_marker}",
    "cmp r13, r11",
    "jne .Lap_nested_probe_failed",
    "mov r10, qword ptr [r14]",
    "mov r11, {ept_source_marker}",
    "cmp r10, r11",
    "jne .Lap_nested_probe_failed",
    "mov r10, qword ptr [rbx + 56]",
    "mov r11, qword ptr [r10]",
    "and r11, 0xfff",
    "mov rdx, qword ptr [rbx + 48]",
    "or r11, rdx",
    "mov qword ptr [r10], r11",
    "mov rcx, {guest_rip_field}",
    "lea rdx, [rip + .Lap_nested_l2_after_first]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rax, {l2_vmresume_magic}",
    "vmresume",
    "jmp .Lap_nested_probe_failed",
    ".Lap_nested_l1_resume_exit:",
    "mov rcx, {exit_reason_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "and edx, 0xffff",
    "cmp edx, 18",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "lea r10, [rip + .Lap_nested_l2_before_invept_vmcall]",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {exit_instruction_len_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, 3",
    "jne .Lap_nested_probe_failed",
    "mov r11, {ept_target_marker}",
    "cmp r13, r11",
    "jne .Lap_nested_probe_failed",
    "lea r10, [rip + .Lap_nested_invept_invalid]",
    "mov qword ptr [rbx + 80], r10",
    "lea r10, [rip + .Lap_nested_invept_invalid_after]",
    "mov qword ptr [rbx + 88], r10",
    "mov rcx, 2",
    ".Lap_nested_invept_invalid:",
    "invept rcx, xmmword ptr [rbx + 64]",
    ".Lap_nested_invept_invalid_after:",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 0x40",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {instruction_error_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {invalid_invalidation_operand_error}",
    "jne .Lap_nested_probe_failed",
    "lea r10, [rip + .Lap_nested_invept_valid]",
    "mov qword ptr [rbx + 80], r10",
    "lea r10, [rip + .Lap_nested_invept_valid_after]",
    "mov qword ptr [rbx + 88], r10",
    "mov rcx, 1",
    ".Lap_nested_invept_valid:",
    "invept rcx, xmmword ptr [rbx + 64]",
    ".Lap_nested_invept_valid_after:",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "test r10d, r10d",
    "jnz .Lap_nested_probe_failed",
    "mov qword ptr [rbx + 96], 0",
    "lea r10, [rip + .Lap_nested_invvpid_invalid]",
    "mov qword ptr [rbx + 112], r10",
    "lea r10, [rip + .Lap_nested_invvpid_invalid_after]",
    "mov qword ptr [rbx + 120], r10",
    "mov rcx, 1",
    ".Lap_nested_invvpid_invalid:",
    "invvpid rcx, xmmword ptr [rbx + 96]",
    ".Lap_nested_invvpid_invalid_after:",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "cmp r10d, 0x40",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {instruction_error_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, {invalid_invalidation_operand_error}",
    "jne .Lap_nested_probe_failed",
    "mov qword ptr [rbx + 96], 1",
    "lea r10, [rip + .Lap_nested_invvpid_valid]",
    "mov qword ptr [rbx + 112], r10",
    "lea r10, [rip + .Lap_nested_invvpid_valid_after]",
    "mov qword ptr [rbx + 120], r10",
    "mov rcx, 1",
    ".Lap_nested_invvpid_valid:",
    "invvpid rcx, xmmword ptr [rbx + 96]",
    ".Lap_nested_invvpid_valid_after:",
    "pushfq",
    "pop r10",
    "and r10d, 0x8d5",
    "test r10d, r10d",
    "jnz .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "lea rdx, [rip + .Lap_nested_l2_after_invept]",
    "vmwrite rcx, rdx",
    "jna .Lap_nested_probe_failed",
    "mov rax, {l2_post_invept_magic}",
    "vmresume",
    "jmp .Lap_nested_probe_failed",
    ".Lap_nested_l1_after_invept_exit:",
    "mov rcx, {exit_reason_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "and edx, 0xffff",
    "cmp edx, 18",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {guest_rip_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "lea r10, [rip + .Lap_nested_l2_after_invept_vmcall]",
    "cmp rdx, r10",
    "jne .Lap_nested_probe_failed",
    "mov rcx, {exit_instruction_len_field}",
    "vmread rdx, rcx",
    "jna .Lap_nested_probe_failed",
    "cmp edx, 3",
    "jne .Lap_nested_probe_failed",
    "mov r11, {ept_second_target_marker}",
    "cmp r13, r11",
    "jne .Lap_nested_probe_failed",
    "vmxoff",
    "jna .Lap_nested_probe_failed",
    "call matrixhv_vmx_flat_enabled",
    "test rax, rax",
    "jnz .Lap_cpuid_done",
    "mov eax, 1",
    "xor ecx, ecx",
    "cpuid",
    "test ecx, 0x20",
    "jnz .Lap_nested_probe_failed",
    "test ecx, 0x80000000",
    "jnz .Lap_cpuid_done",
    "mov eax, 0x40000000",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    "mov eax, 0x40000003",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    "mov eax, 0x40000010",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    "mov eax, 0x40000100",
    "xor ecx, ecx",
    "cpuid",
    "or eax, ebx",
    "or eax, ecx",
    "or eax, edx",
    "jnz .Lap_nested_probe_failed",
    ".Lap_cpuid_done:",
    "mov rax, 0x4856415052454144",
    "vmcall",
    "jmp .Lap_restore",
    ".Lap_nested_probe_failed:",
    "mov rax, {nested_probe_failed}",
    "vmcall",
    ".Lap_restore:",
    "fxrstor64 [rsp + 32]",
    "add rsp, 544",
    "pop r15",
    "pop r14",
    "pop r13",
    "pop r12",
    "pop rdi",
    "pop rsi",
    "pop rbp",
    "pop rbx",
    "popfq",
    "ret",
    nested_probe_failed = const crate::hv_core::vt_resident::RESIDENT_VMCALL_NESTED_PROBE_FAILED,
    guest_rip_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_RIP,
    guest_rsp_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_RSP,
    guest_rflags_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_RFLAGS,
    host_rip_field = const crate::nested::vmcs::VMCS_FIELD_HOST_RIP,
    host_rsp_field = const crate::nested::vmcs::VMCS_FIELD_HOST_RSP,
    exception_bitmap_field = const crate::nested::vmcs::VMCS_FIELD_EXCEPTION_BITMAP,
    guest_cr0_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_CR0,
    guest_cr3_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_CR3,
    guest_cr4_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_CR4,
    host_cr0_field = const crate::nested::vmcs::VMCS_FIELD_HOST_CR0,
    host_cr3_field = const crate::nested::vmcs::VMCS_FIELD_HOST_CR3,
    host_cr4_field = const crate::nested::vmcs::VMCS_FIELD_HOST_CR4,
    guest_sysenter_cs_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_SYSENTER_CS,
    guest_sysenter_esp_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_SYSENTER_ESP,
    guest_sysenter_eip_field = const crate::nested::vmcs::VMCS_FIELD_GUEST_SYSENTER_EIP,
    host_sysenter_cs_field = const crate::nested::vmcs::VMCS_FIELD_HOST_SYSENTER_CS,
    host_sysenter_esp_field = const crate::nested::vmcs::VMCS_FIELD_HOST_SYSENTER_ESP,
    host_sysenter_eip_field = const crate::nested::vmcs::VMCS_FIELD_HOST_SYSENTER_EIP,
    pin_based_control_field = const crate::nested::vmcs::VMCS_FIELD_PIN_BASED_VM_EXEC_CONTROL,
    primary_control_field = const crate::nested::vmcs::VMCS_FIELD_CPU_BASED_VM_EXEC_CONTROL,
    secondary_control_field = const crate::nested::vmcs::VMCS_FIELD_SECONDARY_VM_EXEC_CONTROL,
    vpid_field = const crate::nested::vmcs::VMCS_FIELD_VPID,
    ept_pointer_field = const crate::nested::vmcs::VMCS_FIELD_EPT_POINTER,
    vm_exit_controls_field = const crate::nested::vmcs::VMCS_FIELD_VM_EXIT_CONTROLS,
    vm_entry_controls_field = const crate::nested::vmcs::VMCS_FIELD_VM_ENTRY_CONTROLS,
    primary_activate_secondary_controls = const crate::nested::capabilities::VMX_PRIMARY_ACTIVATE_SECONDARY_CONTROLS,
    secondary_enable_ept = const crate::nested::capabilities::VMX_SECONDARY_ENABLE_EPT,
    secondary_enable_vpid = const crate::nested::capabilities::VMX_SECONDARY_ENABLE_VPID,
    vm_exit_host_address_space_size = const crate::nested::capabilities::VM_EXIT_HOST_ADDRESS_SPACE_SIZE,
    vm_entry_ia32e_mode_guest = const crate::nested::capabilities::VM_ENTRY_IA32E_MODE_GUEST,
    ept_source_marker = const crate::smp::per_cpu::NESTED_EPT_SOURCE_MARKER,
    ept_target_marker = const crate::smp::per_cpu::NESTED_EPT_TARGET_MARKER,
    ept_second_target_marker = const crate::smp::per_cpu::NESTED_EPT_SECOND_TARGET_MARKER,
    exit_reason_field = const crate::nested::vmcs::VMCS_FIELD_VM_EXIT_REASON,
    exit_instruction_len_field = const crate::nested::vmcs::VMCS_FIELD_VM_EXIT_INSTRUCTION_LEN,
    instruction_error_field = const crate::nested::vmcs::VMCS_FIELD_VM_INSTRUCTION_ERROR,
    vmxon_active_error = const crate::nested::instructions::VMXON_IN_VMX_ROOT_ERROR,
    invalid_control_error = const crate::nested::instructions::VM_ENTRY_INVALID_CONTROL_FIELDS_ERROR,
    non_launched_error = const crate::nested::instructions::VMRESUME_NON_LAUNCHED_VMCS_ERROR,
    invalid_invalidation_operand_error = const crate::nested::instructions::INVALID_OPERAND_TO_INVEPT_INVVPID_ERROR,
    vmcs12_test_value = const crate::hv_core::vt_resident::NESTED_VMCS12_TEST_VALUE,
    l2_vmcall_magic = const crate::hv_core::vt_resident::NESTED_L2_VMCALL_MAGIC,
    l2_vmresume_magic = const crate::hv_core::vt_resident::NESTED_L2_VMRESUME_MAGIC,
    l2_post_invept_magic = const crate::hv_core::vt_resident::NESTED_L2_POST_INVEPT_MAGIC,
    sysenter_cs_msr = const crate::arch::x86_64::msr::IA32_SYSENTER_CS,
    sysenter_esp_msr = const crate::arch::x86_64::msr::IA32_SYSENTER_ESP,
    sysenter_eip_msr = const crate::arch::x86_64::msr::IA32_SYSENTER_EIP,
);
